# Before running this with "condor_submit myscript.sub", the
# directories log, error, and output must exist.

universe = vanilla
log = merge.log
error = merge.err

executable = ./merge_table.sh

arguments = 
output = merge.out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files =  http://proxy.chtc.wisc.edu/SQUID/chtc/R361.tar.gz, merge_table.R,temp.tar.gz

request_cpus = 4
request_memory = 4GB
request_disk = 1GB

queue 1